services:
  - type: web
    name: finsight-backend
    env: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: "--max-old-space-size=2048"
    healthCheckPath: /health
    autoDeploy: true 